### PR TITLE
update cli-extra

### PR DESCRIPTION
**Pull request by fanch**

### CODE REVIEW

**Comment by tnut** [comment]
Not able to merge: "This branch has conflicts that must be resolved"
You need to resync your branch with master

**Comment by fanch** [comment]
clementine 1.3.1 and some dependence  for pierre, you can tried it please

**Comment by tnut** [comment]
I'm able to compile clementine on stable branch just need to update libechonest. I also check if nobody use at the moment libechonest as runtime deps... found nobody. I guess clementine could be update on stable branch

**Comment by tnut** [comment]
I did all the updates manualy.
Thanks for the commit, next please one by one

**Pull request closed without merging**
